#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SharedCalc.Droid.Resource", IsApplication=true)]

namespace SharedCalc.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000d
			public const int btnClear = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int btnCount = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int btnDiv = 2131099664;
			
			// aapt resource value: 0x7f060008
			public const int btnMin = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int btnMul = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int btnNum0 = 2131099662;
			
			// aapt resource value: 0x7f060001
			public const int btnNum1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int btnNum2 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int btnNum3 = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int btnNum4 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int btnNum5 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int btnNum6 = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int btnNum7 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int btnNum8 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int btnNum9 = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int btnPlus = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int buttonsLayout = 2131099648;
			
			// aapt resource value: 0x7f060011
			public const int tbScreen = 2131099665;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int ButtonsStyle = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
